# -*- coding: utf-8 -*-
"""Assignment-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fuj8nEe3aejwy6JsRgzwIYT2svN9i9Tm

#Hospital Patient Data Analysis
"""

import pandas as pd

# 1. Load Data
df = pd.read_csv('/content/Billing_Data.csv')
df1 = pd.read_csv('/content/Patient_Data.csv')

# 2. Data Info
print(df1.info())

# 3. Select Required Columns
df2 = df1[['PatientID','Department','Doctor','BillAmount']]

# 4. Drop Unnecessary Columns
df1 = df1.drop(['ReceptionistID', 'CheckInTime'], axis=1)

# 5. Handle Missing Values
mean_value = df1['BillAmount'].mean()
df1['BillAmount'].fillna(mean_value, inplace=True)

# 6. Remove Duplicates
df1.drop_duplicates(inplace=True)

#7. Correct Grouping
dept_bill = df1.groupby('Department')['BillAmount'].sum().reset_index()
print("Total Bill Amount by Department:")
print(dept_bill)

# 8. Merge Datasets
D_merg = pd.merge(df, df1, on='PatientID')
print(D_merg.head())

# 9. Column-wise Concatenation
col_concat = pd.concat([df1['Department'], df1['Doctor']], axis=1)
print("Column-wise Concatenation:")
print(col_concat.head())

# 10. Create New Dataset
lst = [
    [101, 'Cardiology', 'Dr.A', 2500],
    [102, 'Neurology', 'Dr.B', 3500],
    [103, 'Orthopedics', 'Dr.C', 3300],
    [104, 'Dermatology', 'Dr.D', 3200],
]

df3 = pd.DataFrame(lst, columns=['PatientID','Department','Doctor','BillAmount'])

# 11. Row-wise Concatenation
Final_df = pd.concat([df1, df3], axis=0, ignore_index=True)
print("Row-wise Concatenation:")
print(Final_df.head())

"""#Conclusion

- Data was cleaned by removing duplicates and handling missing values.
- Grouping by Department helped analyze total bill amounts correctly.
- Column-wise concatenation combined related columns for better structure.
- Row-wise concatenation was performed after aligning column structure.

Overall, the dataset was properly processed and structured for analysis.
"""